[project]
name = "skillswap-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt>=4.3.0",
    "streamlit>=1.45.1",
    "stripe>=12.1.0",
    "uvicorn>=0.34.2",
]
